name: Terragrunt Workflow
on:
  workflow_call:
    inputs:
      apply:
        description: "Whether the job should apply after plan"
        default: false
        type: string
      environment_name:
        description: "Environment/GCP Account being targeted."
        default: "develop"
        required: true
        type: string
      root:
        description: "Root folder the terragrunt environment lives"
        default: "live"
        type: string
    secrets:
      PROVIDER_NAME:
        description: "OIDC"
        required: true
      SA_EMAIL:
        description: "OIDC"
        required: true

permissions:
  id-token: write
  contents: read
  
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './live/${{inputs.environment_name}}'
        shell: bash
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    #Authenticate with gcloud
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: '${{ secrets.PROVIDER_NAME }}'
        service_account: '${{ secrets.SA_EMAIL }}'

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.1
      with:
        terragrunt_version: latest

    - name: Terragrunt Validate ${{ inputs.environment_name }}
      run: terragrunt run-all validate
      shell: bash

    - name: Terragrunt Plan ${{ inputs.environment_name }}
      run: |
          cd ${{ inputs.root }}/${{ inputs.environment_name }}
          terragrunt run-all plan
      shell: bash

    - name: Terragrunt Apply ${{ inputs.environment_name }}
      if: ${{ inputs.apply == true }}
      run: |
        cd ${{ inputs.environment_name }}
        terragrunt run-all apply
      shell: bash