name: 'Terraform Production Deploy'

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  terragrunt:
    uses: bretthadley/infra/.github/workflows/_terragrunt-workflow.yml@main
    with:
      environment_name: production
      apply: false
    secrets:
      PROVIDER_NAME: ${{secrets.PROVIDER_NAME_PRODUCTION}}
      SA_EMAIL: ${{secrets.SA_EMAIL_PRODUCTION}}