name: 'Terraform Check'

on:
  pull_request:
    branches: [ "!main", "!staging" ]

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
      with:
        workload_identity_provider: '${{ secrets.PROVIDER_NAME }}'
        service_account: '${{ secrets.SA_EMAIL }}'
        environment_name: staging
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      
    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terragrunt
      uses: ./.github/actions/terragrunt
