name: 'Terraform Staging Validate'

on:
  pull_request:
    branches: [ "staging" ]

permissions:
  id-token: write
  contents: read

jobs:
  terragrunt:
    uses: bretthadley/infra/.github/workflows/_terragrunt-workflow.yml@main
    with:
      environment_name: staging
      apply: false
    secrets:
      PROVIDER_NAME: ${{secrets.PROVIDER_NAME_STAGING}}
      SA_EMAIL: ${{secrets.SA_EMAIL_STAGING}}